export const html = `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">    
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@1.*/css/pico.min.css">
    <title>Aneejian ChatGPT Playground Export</title>
</head>
<body>
    <main>
        <div class="container">
            <h1 class="text-center">Aneejian ChatGPT Playground Export</h1>
            <!-- replace me  -->
        </div>
    </main>
</body>
</html>`;

export const python = `
# code generated by Aneejian's ChatGPT Playground
# https://aneejian.com/chatgpt-api-playground
import openai
API_KEY = 'you api key here'
openai.api_key = API_KEY
completion = openai.ChatCompletion.create(
  model="<!-- model name  -->", 
  messages=<!-- messages  -->
)`;
